### ISSUE TITLE
AM/PM with datetime picker

### ISSUE THREAD

**Issue by bwobst** [yn5/curious-datetimepicker#1]
Hi,

I'm not able to get AM/PM working with the datetime picker.  I've set `timeFormat: "hh:mm AA"`, but only get the 24-hour clock.

If I try to set `dateTimeFormat: "dd-MM-yyyy hh:mm AA"`, the date/time selector area goes blank.

Any ideas?

Thanks,
Brian

**Comment by yn5** [comment]
I have updated DateTimePicker to it's latest version: 0.1.25, does this by any chance fix the issue?
